#! /bin/sh
#
# Prepares subs distribution to be in the usual
# state for running './configure', 'make' and
# 'make install'

libtoolize --force --copy \
&& aclocal \
&& automake --gnu --add-missing \
&& autoconf
